version: '3.1'

services:
  db:
    image: mysql
    environment:
      RACK_ENV: local
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quiz
    ports:
        - "3307:3306"

#  web:
#    build: .
#    image: quiz_web
#    ports:
#      - "8080:8080"
#    networks:
#      - my_network
#    depends_on:
#      - db
