#togglz url http://localhost:8080/actuator/togglz
#togglz console ui = http://localhost:8080/togglz-console
#togglz:
#  enabled:
#    true
#  features:
#    DISCOUNT_APPLIED:
#      enabled: true
#  console:
#    secured: true
##    use-management-port: true
##  endpoint:
##    enabled: true
##    id: togglz
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  server:
#    port: 8080
togglz:
  enabled: true # Enable Togglz for the application.
#  feature-enums: # Comma-separated list of fully-qualified feature enum class names.
#  feature-manager-name: # The name of the feature manager.
  features: # The feature states. Only needed if feature states are stored in application properties.
    DISCOUNT_APPLIED:
      enabled: false
#  features-file: # The path to the features file that contains the feature states. Only needed if feature states are stored in external properties file.
#  features-file-min-check-interval: # The minimum amount of time in milliseconds to wait between checks of the file's modification date.
#  cache:
#    enabled: false # Enable feature state caching.
#    time-to-live: 0 # The time after which a cache entry will expire.
#    time-unit: milliseconds # The time unit as java.util.concurrent.TimeUnit enum name (one of "nanoseconds", "microseconds", "milliseconds", "seconds", "minutes", "hours", "days").
  console:
    enabled: true # Enable admin console.
    path: /togglz-console # The path of the admin console when enabled.
    feature-admin-authority: ROLE_ADMIN # The name of the authority that is allowed to access the admin console.
    secured: true # Indicates if the admin console runs in secured mode. If false the application itself should take care of securing the admin console.
#    use-management-port: true # Indicates if the admin console runs on the management port. If no management port is configured it will run on the application port. If set to true the console path will also be prefixed with the management.context-path.
#  endpoint: # Only for Spring Boot 1.x (for Spring Boot 2.x see https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html)
#    id: togglz # The endpoint identifier.
#    enabled: true # Enable actuator endpoint.
#    sensitive: true # Indicates if the endpoint exposes sensitive information.
